language: python
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install pytest-cov

script:
  - travis_wait 999 pytest --cov=.

after_success:
- codecov

